name: food_ui
description: "Aplikasi Pemesanan Makanan RM Solideo Kuliner"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  fluttertoast: ^8.2.12
  # State Management
  provider: ^6.1.1
  image_picker: ^0.8.6  # Utilities
  uuid: ^3.0.7
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  
  # Chart and visualization
  fl_chart: ^0.66.2
  
  # PDF Export
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/prasmanan.png
    - assets/images/ikan_bakar.png
    - assets/images/prasmanann.png
    - assets/images/ikan_bakarr.png
    - assets/images/Minumandingin.png
    - assets/iamgess/Minumandingin.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false