// Status = 0: Pending, 1: Preparing, 2: On the way, 3: Delivered
import 'package:flutter/material.dart';

final List<Map<String, dynamic>> activeOrders = [
  {
    'id': '#ORD-5418',
    'restaurant': 'Pizza Heaven',
    'items': [
      {
        'name': 'Pepperoni Pizza',
        'quantity': 1,
        'price': 16000,
      },
      {
        'name': 'Garlic Bread',
        'quantity': 1,
        'price': 5000,
      },
      {
        'name': 'Coca Cola 1L',
        'quantity': 1,
        'price': 3000,
      },
    ],
    'status': 'Pending',
    'statusCode': 0,
    'date': 'Today, 12:30 PM',
    'estimatedDelivery': '10-15 min',
    'total': 24000,
    'payment': {
      'method': 'Cash on Delivery',
      'status': 'Pending',
      'cardNumber': null,
      'icon': Icons.money,
    },
    'address': {
      'type': 'Home',
      'recipient': 'John Doe',
      'phone': '+62 812-3456-7890',
      'street': 'Jl. Sudirman No. 123',
      'district': 'Karet Tengsin',
      'city': 'Jakarta Pusat',
      'province': 'DKI Jakarta',
      'postalCode': '10220',
      'notes': 'Apartemen Sudirman Tower, Unit 12A',
    },
  },
  {
    'id': '#ORD-5419',
    'restaurant': 'Taco Bell',
    'items': [
      {
        'name': 'French Fries (Large)',
        'quantity': 1,
        'price': 4000,
      },
      {
        'name': 'California Roll (8pcs)',
        'quantity': 1,
        'price': 13000,
      },
      {
        'name': 'Pepsi 1L',
        'quantity': 1,
        'price': 3000,
      },
    ],
    'status': 'Preparing',
    'statusCode': 1,
    'date': 'Today, 12:30 PM',
    'estimatedDelivery': '10-15 min',
    'total': 20000,
    'payment': {
      'method': 'Credit Card',
      'status': 'Paid',
      'cardNumber': '**** **** **** 4321',
      'icon': Icons.credit_card,
    },
    'address': {
      'type': 'Office',
      'recipient': 'John Doe',
      'phone': '+62 812-3456-7890',
      'street': 'Jl. Gatot Subroto Kav. 36-38',
      'district': 'Kuningan',
      'city': 'Jakarta Selatan',
      'province': 'DKI Jakarta',
      'postalCode': '12710',
      'notes': 'Menara BCA, Lantai 25, Ruang 25B',
    },
  },
  {
    'id': '#ORD-5419',
    'restaurant': 'Sushi Master',
    'items': [
      {
        'name': 'Miso Soup',
        'quantity': 1,
        'price': 4000,
      },
      {
        'name': 'Nachos Supreme',
        'quantity': 1,
        'price': 6000,
      },
      {
        'name': 'Pepsi 1L',
        'quantity': 1,
        'price': 3000,
      },
    ],
    'status': 'On the way',
    'statusCode': 2,
    'date': 'Today, 12:30 PM',
    'estimatedDelivery': '10-15 min',
    'total': 13000,
    'payment': {
      'method': 'GoPay',
      'status': 'Paid',
      'cardNumber': null,
      'icon': Icons.account_balance_wallet,
    },
    'address': {
      'type': 'Home',
      'recipient': 'John Doe',
      'phone': '+62 812-3456-7890',
      'street': 'Jl. Sudirman No. 123',
      'district': 'Karet Tengsin',
      'city': 'Jakarta Pusat',
      'province': 'DKI Jakarta',
      'postalCode': '10220',
      'notes': 'Apartemen Sudirman Tower, Unit 12A',
    },
  },
];

final List<Map<String, dynamic>> pastOrders = [
  {
    'id': '#ORD-5317',
    'restaurant': 'Burger King',
    'items': [
      {
        'name': 'Double Whopper',
        'quantity': 1,
        'price': 10000,
      },
      {
        'name': 'French Fries (Large)',
        'quantity': 1,
        'price': 4000,
      },
      {
        'name': 'Sprite 330ml',
        'quantity': 1,
        'price': 2000,
      },
    ],
    'status': 'Delivered',
    'statusCode': 3,
    'date': 'Yesterday, 7:45 PM',
    'deliveredAt': 'Yesterday, 8:20 PM',
    'total': 16000,
    'payment': {
      'method': 'Credit Card',
      'status': 'Paid',
      'cardNumber': '**** **** **** 5678',
      'icon': Icons.credit_card,
    },
    'address': {
      'type': 'Office',
      'recipient': 'John Doe',
      'phone': '+62 812-3456-7890',
      'street': 'Jl. Gatot Subroto Kav. 36-38',
      'district': 'Kuningan',
      'city': 'Jakarta Selatan',
      'province': 'DKI Jakarta',
      'postalCode': '12710',
      'notes': 'Menara BCA, Lantai 25, Ruang 25B',
    },
  },
  {
    'id': '#ORD-5290',
    'restaurant': 'Sushi Master',
    'items': [
      {
        'name': 'California Roll (8pcs)',
        'quantity': 1,
        'price': 13000,
      },
      {
        'name': 'Miso Soup',
        'quantity': 1,
        'price': 4000,
      },
      {
        'name': 'Green Tea',
        'quantity': 1,
        'price': 3000,
      },
    ],
    'status': 'Delivered',
    'statusCode': 3,
    'date': 'May 20, 1:15 PM',
    'deliveredAt': 'May 20, 1:45 PM',
    'total': 20000,
    'payment': {
      'method': 'OVO',
      'status': 'Paid',
      'cardNumber': null,
      'icon': Icons.account_balance_wallet,
    },
    'address': {
      'type': 'Other',
      'recipient': 'Sarah Johnson',
      'phone': '+62 857-1234-5678',
      'street': 'Jl. Kemang Raya No. 45',
      'district': 'Kemang',
      'city': 'Jakarta Selatan',
      'province': 'DKI Jakarta',
      'postalCode': '12730',
      'notes': 'Rumah cat putih, pagar hitam',
    },
  },
  {
    'id': '#ORD-5275',
    'restaurant': 'Taco Bell',
    'items': [
      {
        'name': 'Taco Party Box',
        'quantity': 1,
        'price': 17000,
      },
      {
        'name': 'Nachos Supreme',
        'quantity': 1,
        'price': 6000,
      },
      {
        'name': 'Pepsi 1L',
        'quantity': 1,
        'price': 3000,
      },
    ],
    'status': 'Delivered',
    'statusCode': 3,
    'date': 'May 18, 6:30 PM',
    'deliveredAt': 'May 18, 7:10 PM',
    'total': 26000,
    'payment': {
      'method': 'DANA',
      'status': 'Paid',
      'cardNumber': null,
      'icon': Icons.payment,
    },
    'address': {
      'type': 'Home',
      'recipient': 'John Doe',
      'phone': '+62 812-3456-7890',
      'street': 'Jl. Cikini Raya No. 25',
      'district': 'Cikini',
      'city': 'Jakarta Pusat',
      'province': 'DKI Jakarta',
      'postalCode': '10330',
      'notes': 'Dekat Taman Ismail Marzuki',
    },
  },
];
